### ISSUE TITLE
Emoji for rottenburrito !

### ISSUE THREAD

**Issue by chralp** [chralp/heyburrito#11]

**Comment by tbleckert** [comment]
Two ideas

![rottenburrito](https://user-images.githubusercontent.com/263465/41802143-068c8bb6-767f-11e8-9ecb-566431c375bb.png) ![rottenburrito2](https://user-images.githubusercontent.com/263465/41802144-06a8c39e-767f-11e8-8daa-1bf58a35c2ad.png)

**Comment by chralp** [comment]
What if we just take the default :burrito: and make it green. So it stands out as a "rotten"burrito  ?
