### ISSUE TITLE
Set endpoints for frontend.

### ISSUE THREAD

**Issue by chralp** [chralp/heyburrito#19]
Today these are accessible via socket io
================================
1.
``` 
on => getUserStats
emit => userStats
Result => Will return full user info with stats
```
2
```
on => getReceivedList
emit => receivedList
Result => Will return full list of all users with received stats ( orderd decending )
```
3.
```
on => getGivenList
emit => GivenList
Result => Will return full list of all users with given stats ( orderd decending )
```

**Comment by chralp** [comment]
When issue https://github.com/chralp/heyburrito/issues/16 is fixed we should set up endpoint(s) to return "rottenBurrito stats"

**Comment by chralp** [comment]
1.
on => getUserStats
Parameter => user ( Slack username )
emit => userStats
Result => Will return full user info with stats

2.
on => getReceivedList
Parameter: type ( burrito / rottenburrito ), from ( date ) , to  (date)
emit => receivedList
Result => Will return full list of all users with received stats ( orderd decending )

3.
on => getGivenList
Parameter: type ( burrito / rottenburrito ), from ( date ) , to  (date)
emit => GivenList
Result => Will return full list of all users with given stats ( orderd decending )

Date format => yyyy-mm-dd ?

**Comment by tbleckert** [comment]
All parameters should be optional
