### ISSUE TITLE
Get user stats for given burritos to ?

### ISSUE THREAD

**Issue by chralp** [chralp/heyburrito#20]
Today we can get stats for who have been giving UserOne most burritos.
Can we to it the other way ? Do we want to do it the other way ?
Returning info of who UserOne have been giving must burritos / ruttenburritos to ?

**Comment by tbleckert** [comment]
I think it would at least be a good idea to offer it. With the new database structure it's quite easy to get that data. Just need to add an endpoint for it.

**Comment by tbleckert** [comment]
@chralp Maybe this data should just be included in the getUserStats endpoint right?
