### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by chralp** [chralp/heyburrito#23]
We want to changing the name of the application from heyburrito to something else. Since the application is not bounden to burritos. It was more a fun way to get this project started.
Drop some names and star the good ones.

**Comment by chralp** [comment]
creddr

**Comment by chralp** [comment]
cremoj

**Comment by marlev** [comment]
dunderhonung
thunder-honey
spinach
popeye
kablam
kaboom
honey
juice
mojo
leet
swag
1337
TOOTSIES
fika
Double Rainbow (DR)
gawd

**Comment by tbleckert** [comment]
The only reasonable and logical move here is to name it **Oha**. Since all your (@chralp) commits and PRs are either named Oha or Ohana I see no other choice than to name it that.

And to reference the only useful dictionary (Urban dictionary obvs):

> Oha is a word when you see or hear a shocking thing. Turkish people use them. Not much to say.

For example:

> Oha look at this app!

You know it's true.

**Comment by chralp** [comment]
Putting this on hold, heyburito rocks !:D
